version: '3'

services:
  db:
    image: postgres:15
    env_file:
      - sample.env
    environment:
      - TZ=UTC
    container_name: coupon-codes-database

  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8000:8000
    depends_on:
      - db
    container_name: coupon-codes-app
