from enum import StrEnum


class DiscountTypesEnum(StrEnum):
    PERCENTAGE = "PERCENTAGE"
    FIXED_AMOUNT_GENERAL_PUBLIC = "FIXED_AMOUNT_GENERAL_PUBLIC"
    FIXED_AMOUNT_FIRST_PURCHASE = "FIXED_AMOUNT_FIRST_PURCHASE"
